# Generated by Django 4.1.3 on 2022-12-01 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_alter_analysis_options_analysis_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysis',
            old_name='data',
            new_name='date',
        ),
    ]
